services:
  db:
    image: mysql:8.0
    container_name: student_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306" # host:container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: student_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


